/** @type {import('tailwindcss').Config} */
module.exports = {
	content: ["./app/**/*.{js,jsx,ts,tsx}"],
	theme: {
		extend: {
			colors: {
				primary: {
					50: "var(--color-primary-50)",
					100: "var(--color-primary-100)",
					200: "var(--color-primary-200)",
					300: "var(--color-primary-300)",
					400: "var(--color-primary-400)",
					500: "var(--color-primary-500)",
					600: "var(--color-primary-600)",
					700: "var(--color-primary-700)",
					800: "var(--color-primary-800)",
					900: "var(--color-primary-900)",
					DEFAULT: "var(--color-primary-300)",
					foreground: "var(--primary-foreground)",
				},
				secondary: {
					50: "var(--color-secondary-50)",
					100: "var(--color-secondary-100)",
					200: "var(--color-secondary-200)",
					300: "var(--color-secondary-300)",
					400: "var(--color-secondary-400)",
					500: "var(--color-secondary-500)",
					600: "var(--color-secondary-600)",
					700: "var(--color-secondary-700)",
					800: "var(--color-secondary-800)",
					900: "var(--color-secondary-900)",
					DEFAULT: "var(--color-secondary-500)",
					foreground: "var(--secondary-foreground)",
					"low-em": "var(--color-secondary-low-em)",
				},
				background: "var(--background)",
				foreground: "var(--foreground)",
				card: { DEFAULT: "var(--card)", foreground: "var(--card-foreground)" },
				popover: {
					DEFAULT: "var(--popover)",
					foreground: "var(--popover-foreground)",
				},
				muted: {
					DEFAULT: "var(--muted)",
					foreground: "var(--muted-foreground)",
				},
				accent: {
					DEFAULT: "var(--accent)",
					foreground: "var(--accent-foreground)",
				},
				destructive: {
					DEFAULT: "var(--destructive)",
					foreground: "var(--destructive-foreground)",
				},
				border: "var(--border)",
				input: "var(--input)",
				ring: "var(--ring)",
				chart: {
					1: "var(--chart-1)",
					2: "var(--chart-2)",
					3: "var(--chart-3)",
					4: "var(--chart-4)",
					5: "var(--chart-5)",
				},
				sidebar: {
					DEFAULT: "var(--sidebar)",
					foreground: "var(--sidebar-foreground)",
					primary: "var(--sidebar-primary)",
					"primary-foreground": "var(--sidebar-primary-foreground)",
					accent: "var(--sidebar-accent)",
					"accent-foreground": "var(--sidebar-accent-foreground)",
					border: "var(--sidebar-border)",
					ring: "var(--sidebar-ring)",
				},
				"light-gray": {
					25: "var(--color-light-gray-25)",
					50: "var(--color-light-gray-50)",
					100: "var(--color-light-gray-100)",
					200: "var(--color-light-gray-200)",
					300: "var(--color-light-gray-300)",
					400: "var(--color-light-gray-400)",
					500: "var(--color-light-gray-500)",
					600: "var(--color-light-gray-600)",
					700: "var(--color-light-gray-700)",
					800: "var(--color-light-gray-800)",
					900: "var(--color-light-gray-900)",
				},
				"dark-gray": {
					50: "var(--color-dark-gray-50)",
					100: "var(--color-dark-gray-100)",
					200: "var(--color-dark-gray-200)",
					300: "var(--color-dark-gray-300)",
					400: "var(--color-dark-gray-400)",
					500: "var(--color-dark-gray-500)",
					600: "var(--color-dark-gray-600)",
					700: "var(--color-dark-gray-700)",
					800: "var(--color-dark-gray-800)",
					900: "var(--color-dark-gray-900)",
				},
				info: {
					50: "var(--color-info-50)",
					100: "var(--color-info-100)",
					200: "var(--color-info-200)",
					300: "var(--color-info-300)",
					400: "var(--color-info-400)",
					500: "var(--color-info-500)",
					600: "var(--color-info-600)",
					700: "var(--color-info-700)",
					800: "var(--color-info-800)",
					900: "var(--color-info-900)",
				},
				success: {
					50: "var(--color-success-50)",
					100: "var(--color-success-100)",
					200: "var(--color-success-200)",
					300: "var(--color-success-300)",
					400: "var(--color-success-400)",
					500: "var(--color-success-500)",
					600: "var(--color-success-600)",
					700: "var(--color-success-700)",
					800: "var(--color-success-800)",
					900: "var(--color-success-900)",
				},
				warning: {
					50: "var(--color-warning-50)",
					100: "var(--color-warning-100)",
					200: "var(--color-warning-200)",
					300: "var(--color-warning-300)",
					400: "var(--color-warning-400)",
					500: "var(--color-warning-500)",
					600: "var(--color-warning-600)",
					700: "var(--color-warning-700)",
					800: "var(--color-warning-800)",
					900: "var(--color-warning-900)",
				},
				danger: {
					50: "var(--color-danger-50)",
					100: "var(--color-danger-100)",
					200: "var(--color-danger-200)",
					300: "var(--color-danger-300)",
					400: "var(--color-danger-400)",
					500: "var(--color-danger-500)",
					600: "var(--color-danger-600)",
					700: "var(--color-danger-700)",
					800: "var(--color-danger-800)",
					900: "var(--color-danger-900)",
				},
				hero: {
					low: "var(--color-hero-low)",
					med: "var(--color-hero-med)",
					high: "var(--color-hero-high)",
				},
				glass: {
					orange: "var(--glass-orange)",
					"orange-hover": "var(--glass-orange-hover)",
					blue: "var(--glass-blue)",
					"blue-hover": "var(--glass-blue-hover)",
					backdrop: "var(--glass-backdrop)",
					border: "var(--glass-border)",
				},
			},
			borderRadius: {
				lg: "var(--radius)",
				md: "calc(var(--radius) - 2px)",
				sm: "calc(var(--radius) - 4px)",
			},
			fontFamily: { manrope: ["Manrope", "sans-serif"] },
		},
	},
	plugins: [],
};
